### ISSUE TITLE
[MVC-001] : Url for images and other resources are incorrect 

### ISSUE THREAD

**Issue by rida-fatima-aspose** [groupdocs-signature/GroupDocs.Signature-for-.NET#17]
This issue was originally raised via forum thread:
http://groupdocs.com/Community/forums/thread/16721/groupdocs.signature-ui-application-iis-hosting.aspx

The project once run in debug mode using local IIS shows no resources as the links are application relative. The links needed to be absolute URLs or application relative root paths.
Moreover, gdSignatureHostUrl from _Layout.cshtml is used in JavaScript funcions in DocViewer.all.part1.js and DocViewer.all.part2.js
Also those code snippets affects URL creating in JS:

var gdSignaturePrefix ='gd-signature';
ViewContext.AppPath = '/gd-signature/signature2/';
ViewContext.PortalServiceHost = '/gd-signature/signature2/';
var gdSignatureHostUrl = '';
Please investigate this issue and try to fix it as soon as possible

**Comment by bobkovalex** [comment]
Issue is not valid anymore
