### ISSUE TITLE
[MVC-002] : Unable to open UI in Visual Studio

### ISSUE THREAD

**Issue by samicheemagroupdocs** [groupdocs-signature/GroupDocs.Signature-for-.NET#38]
I am trying to load project in Visual Studio 2015 using .sln file in project directory but getting a message "load failed" in solution explorer 
![load failed](https://user-images.githubusercontent.com/29034002/34466423-20794e46-eef4-11e7-9739-7e7934f7e326.png)

**Comment by saqibmasood** [comment]
The project has been fixed.
