### ISSUE TITLE
[MVC-003] : Unable to run application using IIS

### ISSUE THREAD

**Issue by samicheemagroupdocs** [groupdocs-signature/GroupDocs.Signature-for-.NET#42]
I am getting resource not found error while trying to run the application using Internet Information Services(IIS) 7.5. The version of the GroupDocs.Signature API is 3.0.0. Please find attached screenshot of error summary for further reference.
![error detail](https://user-images.githubusercontent.com/29034002/37090144-fb4fa278-2224-11e8-963b-93ab44c53779.png)

**Comment by saqibmasood** [comment]
@samicheemagroupdocs Cannot reproduce the issue at my side. Kindly share some details about the environment and how was the project deployed on IIS.
