### ISSUE TITLE
[MVC-005] : Getting session Null in SignatureController.cs class

### ISSUE THREAD

**Issue by samicheemagroupdocs** [groupdocs-signature/GroupDocs.Signature-for-.NET#44]
This issue was originally raised via forum thread:
https://forum.groupdocs.com/t/groupdocs-signature-on-pdf-in-net-mvc/5822/7

When I sign the document and then click confirm signature, it navigates to **SignatureController** on **PublicSignDocument** method. I am trying to get session in this class but getting null while if I go back to application page it has session.

**Comment by bobkovalex** [comment]
Issue is not valid anymore
